//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.01 at 03:58:04 PM IST 
//


package com.twc.fatcaone.notification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;Component xmlns="urn:fatca:fatcanotificationbase" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;DictionaryEntryNm&gt;Action Requested Group Type&lt;/DictionaryEntryNm&gt;&lt;MajorVersionNum&gt;1&lt;/MajorVersionNum&gt;&lt;MinorVersionNum&gt;1&lt;/MinorVersionNum&gt;&lt;VersionEffectiveBeginDt&gt;2014-12-02&lt;/VersionEffectiveBeginDt&gt;&lt;VersionDescriptionTxt&gt;Initial Version&lt;/VersionDescriptionTxt&gt;&lt;DescriptionTxt&gt;Details of Action Requested Group Type&lt;/DescriptionTxt&gt;
 * 				&lt;/Component&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for ActionRequestedGrpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionRequestedGrpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}ActionRequestedTxt"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}ActionRequestedDueDateTxt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionRequestedGrpType", propOrder = {
    "actionRequestedTxt",
    "actionRequestedDueDateTxt"
})
public class ActionRequestedGrpType {

    @XmlElement(name = "ActionRequestedTxt", required = true)
    protected String actionRequestedTxt;
    @XmlElement(name = "ActionRequestedDueDateTxt", required = true)
    protected String actionRequestedDueDateTxt;

    /**
     * Gets the value of the actionRequestedTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionRequestedTxt() {
        return actionRequestedTxt;
    }

    /**
     * Sets the value of the actionRequestedTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionRequestedTxt(String value) {
        this.actionRequestedTxt = value;
    }

    /**
     * Gets the value of the actionRequestedDueDateTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionRequestedDueDateTxt() {
        return actionRequestedDueDateTxt;
    }

    /**
     * Sets the value of the actionRequestedDueDateTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionRequestedDueDateTxt(String value) {
        this.actionRequestedDueDateTxt = value;
    }

}
