//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.01 at 03:58:04 PM IST 
//


package com.twc.fatcaone.notification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;Component xmlns="urn:fatca:fatcainterimvalidfilenotification" xmlns:fnb="urn:fatca:fatcanotificationbase" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;DictionaryEntryNm&gt;Type for FATCA Notification for Interim Valid Files&lt;/DictionaryEntryNm&gt;&lt;MajorVersionNum&gt;1&lt;/MajorVersionNum&gt;&lt;MinorVersionNum&gt;4&lt;/MinorVersionNum&gt;&lt;VersionEffectiveBeginDt&gt;2014-12-02&lt;/VersionEffectiveBeginDt&gt;&lt;VersionDescriptionTxt&gt;Version 1.4&lt;/VersionDescriptionTxt&gt;&lt;Description&gt;Contains the type details of FATCA Notification for Interim Valid Files (i.e. schema validated files)&lt;/Description&gt;
 * 				&lt;/Component&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for FATCAValidFileNotificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FATCAValidFileNotificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FATCANotificationHeaderGrp"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}OriginalFileMetadataGrp"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}OriginalFileMessageSpecGrp"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}NotificationContentTxt"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}OriginalFileProcessingDataGrp"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}HCTATreatyStampTxt" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.4" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FATCAValidFileNotificationType", namespace = "urn:fatca:fatcainterimvalidfilenotification", propOrder = {
    "fatcaNotificationHeaderGrp",
    "originalFileMetadataGrp",
    "originalFileMessageSpecGrp",
    "notificationContentTxt",
    "originalFileProcessingDataGrp",
    "hctaTreatyStampTxt"
})
public class FATCAValidFileNotificationType {

    @XmlElement(name = "FATCANotificationHeaderGrp", namespace = "urn:fatca:fatcanotificationbase", required = true)
    protected FATCANotificationHeaderGrpType fatcaNotificationHeaderGrp;
    @XmlElement(name = "OriginalFileMetadataGrp", namespace = "urn:fatca:fatcanotificationbase", required = true)
    protected OriginalFileMetadataGrpType originalFileMetadataGrp;
    @XmlElement(name = "OriginalFileMessageSpecGrp", namespace = "urn:fatca:fatcanotificationbase", required = true)
    protected OriginalFileMessageSpecGrpType originalFileMessageSpecGrp;
    @XmlElement(name = "NotificationContentTxt", namespace = "urn:fatca:fatcanotificationbase", required = true)
    protected String notificationContentTxt;
    @XmlElement(name = "OriginalFileProcessingDataGrp", namespace = "urn:fatca:fatcanotificationbase", required = true)
    protected OriginalFileProcessingDataGrpType originalFileProcessingDataGrp;
    @XmlElement(name = "HCTATreatyStampTxt", namespace = "urn:fatca:fatcanotificationbase")
    protected String hctaTreatyStampTxt;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the fatcaNotificationHeaderGrp property.
     * 
     * @return
     *     possible object is
     *     {@link FATCANotificationHeaderGrpType }
     *     
     */
    public FATCANotificationHeaderGrpType getFATCANotificationHeaderGrp() {
        return fatcaNotificationHeaderGrp;
    }

    /**
     * Sets the value of the fatcaNotificationHeaderGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link FATCANotificationHeaderGrpType }
     *     
     */
    public void setFATCANotificationHeaderGrp(FATCANotificationHeaderGrpType value) {
        this.fatcaNotificationHeaderGrp = value;
    }

    /**
     * Gets the value of the originalFileMetadataGrp property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalFileMetadataGrpType }
     *     
     */
    public OriginalFileMetadataGrpType getOriginalFileMetadataGrp() {
        return originalFileMetadataGrp;
    }

    /**
     * Sets the value of the originalFileMetadataGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalFileMetadataGrpType }
     *     
     */
    public void setOriginalFileMetadataGrp(OriginalFileMetadataGrpType value) {
        this.originalFileMetadataGrp = value;
    }

    /**
     * Gets the value of the originalFileMessageSpecGrp property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalFileMessageSpecGrpType }
     *     
     */
    public OriginalFileMessageSpecGrpType getOriginalFileMessageSpecGrp() {
        return originalFileMessageSpecGrp;
    }

    /**
     * Sets the value of the originalFileMessageSpecGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalFileMessageSpecGrpType }
     *     
     */
    public void setOriginalFileMessageSpecGrp(OriginalFileMessageSpecGrpType value) {
        this.originalFileMessageSpecGrp = value;
    }

    /**
     * Gets the value of the notificationContentTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotificationContentTxt() {
        return notificationContentTxt;
    }

    /**
     * Sets the value of the notificationContentTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotificationContentTxt(String value) {
        this.notificationContentTxt = value;
    }

    /**
     * Gets the value of the originalFileProcessingDataGrp property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalFileProcessingDataGrpType }
     *     
     */
    public OriginalFileProcessingDataGrpType getOriginalFileProcessingDataGrp() {
        return originalFileProcessingDataGrp;
    }

    /**
     * Sets the value of the originalFileProcessingDataGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalFileProcessingDataGrpType }
     *     
     */
    public void setOriginalFileProcessingDataGrp(OriginalFileProcessingDataGrpType value) {
        this.originalFileProcessingDataGrp = value;
    }

    /**
     * Gets the value of the hctaTreatyStampTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHCTATreatyStampTxt() {
        return hctaTreatyStampTxt;
    }

    /**
     * Sets the value of the hctaTreatyStampTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHCTATreatyStampTxt(String value) {
        this.hctaTreatyStampTxt = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.4";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
