//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.01 at 03:58:04 PM IST 
//


package com.twc.fatcaone.notification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;Component xmlns="urn:fatca:fatcanotificationbase" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;DictionaryEntryNm&gt;FATCA Notification Header Group Type&lt;/DictionaryEntryNm&gt;&lt;MajorVersionNum&gt;1&lt;/MajorVersionNum&gt;&lt;MinorVersionNum&gt;1&lt;/MinorVersionNum&gt;&lt;VersionEffectiveBeginDt&gt;2014-11-17&lt;/VersionEffectiveBeginDt&gt;&lt;VersionDescriptionTxt&gt;Initial Version&lt;/VersionDescriptionTxt&gt;&lt;DescriptionTxt&gt;Type for detail information about FATCA notification header&lt;/DescriptionTxt&gt;
 * 				&lt;/Component&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for FATCANotificationHeaderGrpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FATCANotificationHeaderGrpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FATCANotificationCreateTs"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FATCANotificationRefId"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FATCANotificationCd"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FATCAEntitySenderId"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FATCAEntityReceiverId"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}CopiedToFATCAEntityId" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}ContactInformationTxt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FATCANotificationHeaderGrpType", propOrder = {
    "fatcaNotificationCreateTs",
    "fatcaNotificationRefId",
    "fatcaNotificationCd",
    "fatcaEntitySenderId",
    "fatcaEntityReceiverId",
    "copiedToFATCAEntityId",
    "contactInformationTxt"
})
public class FATCANotificationHeaderGrpType {

    @XmlElement(name = "FATCANotificationCreateTs", required = true)
    protected String fatcaNotificationCreateTs;
    @XmlElement(name = "FATCANotificationRefId", required = true)
    protected String fatcaNotificationRefId;
    @XmlElement(name = "FATCANotificationCd", required = true)
    protected FATCANotificationCdType fatcaNotificationCd;
    @XmlElement(name = "FATCAEntitySenderId", required = true)
    protected String fatcaEntitySenderId;
    @XmlElement(name = "FATCAEntityReceiverId", required = true)
    protected String fatcaEntityReceiverId;
    @XmlElement(name = "CopiedToFATCAEntityId")
    protected String copiedToFATCAEntityId;
    @XmlElement(name = "ContactInformationTxt")
    protected String contactInformationTxt;

    /**
     * Gets the value of the fatcaNotificationCreateTs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFATCANotificationCreateTs() {
        return fatcaNotificationCreateTs;
    }

    /**
     * Sets the value of the fatcaNotificationCreateTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFATCANotificationCreateTs(String value) {
        this.fatcaNotificationCreateTs = value;
    }

    /**
     * Gets the value of the fatcaNotificationRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFATCANotificationRefId() {
        return fatcaNotificationRefId;
    }

    /**
     * Sets the value of the fatcaNotificationRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFATCANotificationRefId(String value) {
        this.fatcaNotificationRefId = value;
    }

    /**
     * Gets the value of the fatcaNotificationCd property.
     * 
     * @return
     *     possible object is
     *     {@link FATCANotificationCdType }
     *     
     */
    public FATCANotificationCdType getFATCANotificationCd() {
        return fatcaNotificationCd;
    }

    /**
     * Sets the value of the fatcaNotificationCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link FATCANotificationCdType }
     *     
     */
    public void setFATCANotificationCd(FATCANotificationCdType value) {
        this.fatcaNotificationCd = value;
    }

    /**
     * Gets the value of the fatcaEntitySenderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFATCAEntitySenderId() {
        return fatcaEntitySenderId;
    }

    /**
     * Sets the value of the fatcaEntitySenderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFATCAEntitySenderId(String value) {
        this.fatcaEntitySenderId = value;
    }

    /**
     * Gets the value of the fatcaEntityReceiverId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFATCAEntityReceiverId() {
        return fatcaEntityReceiverId;
    }

    /**
     * Sets the value of the fatcaEntityReceiverId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFATCAEntityReceiverId(String value) {
        this.fatcaEntityReceiverId = value;
    }

    /**
     * Gets the value of the copiedToFATCAEntityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopiedToFATCAEntityId() {
        return copiedToFATCAEntityId;
    }

    /**
     * Sets the value of the copiedToFATCAEntityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopiedToFATCAEntityId(String value) {
        this.copiedToFATCAEntityId = value;
    }

    /**
     * Gets the value of the contactInformationTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactInformationTxt() {
        return contactInformationTxt;
    }

    /**
     * Sets the value of the contactInformationTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactInformationTxt(String value) {
        this.contactInformationTxt = value;
    }

}
