//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.01 at 03:58:04 PM IST 
//


package com.twc.fatcaone.notification;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FATCANotificationCdType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FATCANotificationCdType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NDW"/>
 *     &lt;enumeration value="NDC"/>
 *     &lt;enumeration value="NDP"/>
 *     &lt;enumeration value="NSC"/>
 *     &lt;enumeration value="NTD"/>
 *     &lt;enumeration value="NVS"/>
 *     &lt;enumeration value="NSV"/>
 *     &lt;enumeration value="NMR"/>
 *     &lt;enumeration value="NDM"/>
 *     &lt;enumeration value="NDR"/>
 *     &lt;enumeration value="NIM"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FATCANotificationCdType")
@XmlEnum
public enum FATCANotificationCdType {


    /**
     * Failed Download Notification (N1)
     * 
     */
    NDW,

    /**
     * Failed Decryption Notification (N2)
     * 
     */
    NDC,

    /**
     * Failed Decompression Notification (N2.1)
     * 
     */
    NDP,

    /**
     * Failed Signature Check Notification (N2.2)
     * 
     */
    NSC,

    /**
     * Failed Threat Detection Notification (N3.1)
     * 
     */
    NTD,

    /**
     * Failed Virus Scan Notification (N3.2)
     * 
     */
    NVS,

    /**
     * Failed Schema Notification (N4)
     * 
     */
    NSV,

    /**
     * Invalid MessageRefId Notification (N4.1)
     * 
     */
    NMR,

    /**
     * Duplicate MessageRefId Notification (N4.2) 
     * 
     */
    NDM,

    /**
     * File Containing Invalid DocRefId Notification (N4.3)
     * 
     */
    NDR,

    /**
     * Interim Valid File Notification (N5.3)
     * 
     */
    NIM;

    public String value() {
        return name();
    }

    public static FATCANotificationCdType fromValue(String v) {
        return valueOf(v);
    }

}
