//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.01 at 03:58:04 PM IST 
//


package com.twc.fatcaone.notification;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;Component xmlns="urn:fatca:fatcanotificationbase" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;DictionaryEntryNm&gt;Field Error Group Type&lt;/DictionaryEntryNm&gt;&lt;MajorVersionNum&gt;1&lt;/MajorVersionNum&gt;&lt;MinorVersionNum&gt;0&lt;/MinorVersionNum&gt;&lt;VersionEffectiveBeginDt&gt;2014-08-12&lt;/VersionEffectiveBeginDt&gt;&lt;VersionDescriptionTxt&gt;Initial Version&lt;/VersionDescriptionTxt&gt;&lt;DescriptionTxt&gt;Type for details about FATCA report field errors. (note that PartNum and LineNum are only applicable to paper based reports.)&lt;/DescriptionTxt&gt;
 * 				&lt;/Component&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for FieldErrorGrpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FieldErrorGrpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FieldPartNum" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FieldLineNum" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FieldNm"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FieldErrorCd"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FieldErrorTxt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FieldErrorGrpType", propOrder = {
    "fieldPartNum",
    "fieldLineNum",
    "fieldNm",
    "fieldErrorCd",
    "fieldErrorTxt"
})
public class FieldErrorGrpType {

    @XmlElement(name = "FieldPartNum")
    protected BigInteger fieldPartNum;
    @XmlElement(name = "FieldLineNum")
    protected BigInteger fieldLineNum;
    @XmlElement(name = "FieldNm", required = true)
    protected String fieldNm;
    @XmlElement(name = "FieldErrorCd", required = true)
    protected String fieldErrorCd;
    @XmlElement(name = "FieldErrorTxt", required = true)
    protected String fieldErrorTxt;

    /**
     * Gets the value of the fieldPartNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFieldPartNum() {
        return fieldPartNum;
    }

    /**
     * Sets the value of the fieldPartNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFieldPartNum(BigInteger value) {
        this.fieldPartNum = value;
    }

    /**
     * Gets the value of the fieldLineNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFieldLineNum() {
        return fieldLineNum;
    }

    /**
     * Sets the value of the fieldLineNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFieldLineNum(BigInteger value) {
        this.fieldLineNum = value;
    }

    /**
     * Gets the value of the fieldNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldNm() {
        return fieldNm;
    }

    /**
     * Sets the value of the fieldNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldNm(String value) {
        this.fieldNm = value;
    }

    /**
     * Gets the value of the fieldErrorCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldErrorCd() {
        return fieldErrorCd;
    }

    /**
     * Sets the value of the fieldErrorCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldErrorCd(String value) {
        this.fieldErrorCd = value;
    }

    /**
     * Gets the value of the fieldErrorTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldErrorTxt() {
        return fieldErrorTxt;
    }

    /**
     * Sets the value of the fieldErrorTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldErrorTxt(String value) {
        this.fieldErrorTxt = value;
    }

}
