//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.01 at 03:58:04 PM IST 
//


package com.twc.fatcaone.notification;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FileTypeCdType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FileTypeCdType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NEW"/>
 *     &lt;enumeration value="REV"/>
 *     &lt;enumeration value="DUP"/>
 *     &lt;enumeration value="UNK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FileTypeCdType")
@XmlEnum
public enum FileTypeCdType {


    /**
     * NEW_FILE - New File
     * 
     */
    NEW,

    /**
     * REVISED_FILE - Revised File
     * 
     */
    REV,

    /**
     * DUPLICATE_FILE - Duplicate File
     * 
     */
    DUP,

    /**
     * UNKNOWN - Unknown File Type
     * 
     */
    UNK;

    public String value() {
        return name();
    }

    public static FileTypeCdType fromValue(String v) {
        return valueOf(v);
    }

}
