//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.01 at 03:58:04 PM IST 
//


package com.twc.fatcaone.notification;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.twc.fatcaone.notification package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FieldErrorCd_QNAME = new QName("urn:fatca:fatcanotificationbase", "FieldErrorCd");
    private final static QName _SenderFileId_QNAME = new QName("urn:fatca:fatcanotificationbase", "SenderFileId");
    private final static QName _OriginalFileMessageSpecGrp_QNAME = new QName("urn:fatca:fatcanotificationbase", "OriginalFileMessageSpecGrp");
    private final static QName _AccountReportRecordCnt_QNAME = new QName("urn:fatca:fatcanotificationbase", "AccountReportRecordCnt");
    private final static QName _CorrDocRefId_QNAME = new QName("urn:fatca:fatcanotificationbase", "CorrDocRefId");
    private final static QName _AttachedPaperSubmissionFileNm_QNAME = new QName("urn:fatca:fatcanotificationbase", "AttachedPaperSubmissionFileNm");
    private final static QName _DuplicateRecordInd_QNAME = new QName("urn:fatca:fatcanotificationbase", "DuplicateRecordInd");
    private final static QName _ActionRequestedGrp_QNAME = new QName("urn:fatca:fatcanotificationbase", "ActionRequestedGrp");
    private final static QName _ReportingFINm_QNAME = new QName("urn:fatca:fatcanotificationbase", "ReportingFINm");
    private final static QName _AccountCnt_QNAME = new QName("urn:fatca:fatcanotificationbase", "AccountCnt");
    private final static QName _FinancialInstitutionCnt_QNAME = new QName("urn:fatca:fatcanotificationbase", "FinancialInstitutionCnt");
    private final static QName _FATCANotificationCd_QNAME = new QName("urn:fatca:fatcanotificationbase", "FATCANotificationCd");
    private final static QName _FATCANotificationRefId_QNAME = new QName("urn:fatca:fatcanotificationbase", "FATCANotificationRefId");
    private final static QName _AccountPoolReportTypeCd_QNAME = new QName("urn:fatca:fatcanotificationbase", "AccountPoolReportTypeCd");
    private final static QName _MessageRefId_QNAME = new QName("urn:fatca:fatcanotificationbase", "MessageRefId");
    private final static QName _IDESTransmissionId_QNAME = new QName("urn:fatca:fatcanotificationbase", "IDESTransmissionId");
    private final static QName _OriginalFileProcessingDataGrp_QNAME = new QName("urn:fatca:fatcanotificationbase", "OriginalFileProcessingDataGrp");
    private final static QName _AccountBalanceAmount_QNAME = new QName("urn:fatca:fatcanotificationbase", "AccountBalanceAmount");
    private final static QName _FileTypeCd_QNAME = new QName("urn:fatca:fatcanotificationbase", "FileTypeCd");
    private final static QName _FieldNm_QNAME = new QName("urn:fatca:fatcanotificationbase", "FieldNm");
    private final static QName _SendingCompanyGIIN_QNAME = new QName("urn:fatca:fatcanotificationbase", "SendingCompanyGIIN");
    private final static QName _PooledReportInd_QNAME = new QName("urn:fatca:fatcanotificationbase", "PooledReportInd");
    private final static QName _OriginalIDESTransmissionId_QNAME = new QName("urn:fatca:fatcanotificationbase", "OriginalIDESTransmissionId");
    private final static QName _CorrMessageRefId_QNAME = new QName("urn:fatca:fatcanotificationbase", "CorrMessageRefId");
    private final static QName _TransmittingCountryCd_QNAME = new QName("urn:fatca:fatcanotificationbase", "TransmittingCountryCd");
    private final static QName _FATCAEntitySenderId_QNAME = new QName("urn:fatca:fatcanotificationbase", "FATCAEntitySenderId");
    private final static QName _RecordIdentifier_QNAME = new QName("urn:fatca:fatcanotificationbase", "RecordIdentifier");
    private final static QName _RequestSubmissionDt_QNAME = new QName("urn:fatca:fatcanotificationbase", "RequestSubmissionDt");
    private final static QName _ActionRequestedTxt_QNAME = new QName("urn:fatca:fatcanotificationbase", "ActionRequestedTxt");
    private final static QName _ReportingFIGIIN_QNAME = new QName("urn:fatca:fatcanotificationbase", "ReportingFIGIIN");
    private final static QName _CountryCd_QNAME = new QName("urn:fatca:fatcanotificationbase", "CountryCd");
    private final static QName _PotentialEffectTxt_QNAME = new QName("urn:fatca:fatcanotificationbase", "PotentialEffectTxt");
    private final static QName _PaperRecordInd_QNAME = new QName("urn:fatca:fatcanotificationbase", "PaperRecordInd");
    private final static QName _MessageTypeCd_QNAME = new QName("urn:fatca:fatcanotificationbase", "MessageTypeCd");
    private final static QName _ContactInformationTxt_QNAME = new QName("urn:fatca:fatcanotificationbase", "ContactInformationTxt");
    private final static QName _NotificationContentTxt_QNAME = new QName("urn:fatca:fatcanotificationbase", "NotificationContentTxt");
    private final static QName _HCTATreatyStampTxt_QNAME = new QName("urn:fatca:fatcanotificationbase", "HCTATreatyStampTxt");
    private final static QName _IDESSendingTs_QNAME = new QName("urn:fatca:fatcanotificationbase", "IDESSendingTs");
    private final static QName _FieldErrorTxt_QNAME = new QName("urn:fatca:fatcanotificationbase", "FieldErrorTxt");
    private final static QName _ReceivingCountryCd_QNAME = new QName("urn:fatca:fatcanotificationbase", "ReceivingCountryCd");
    private final static QName _HCTAAddressGrp_QNAME = new QName("urn:fatca:fatcanotificationbase", "HCTAAddressGrp");
    private final static QName _UncompressedFileSizeKBQty_QNAME = new QName("urn:fatca:fatcanotificationbase", "UncompressedFileSizeKBQty");
    private final static QName _AttachedCARFileNm_QNAME = new QName("urn:fatca:fatcanotificationbase", "AttachedCARFileNm");
    private final static QName _DocTypeIndicCd_QNAME = new QName("urn:fatca:fatcanotificationbase", "DocTypeIndicCd");
    private final static QName _FieldPartNum_QNAME = new QName("urn:fatca:fatcanotificationbase", "FieldPartNum");
    private final static QName _RecordErrorTypeCd_QNAME = new QName("urn:fatca:fatcanotificationbase", "RecordErrorTypeCd");
    private final static QName _RequestAuthorizerNm_QNAME = new QName("urn:fatca:fatcanotificationbase", "RequestAuthorizerNm");
    private final static QName _FATCANotificationHeaderGrp_QNAME = new QName("urn:fatca:fatcanotificationbase", "FATCANotificationHeaderGrp");
    private final static QName _FATCANotificationCreateTs_QNAME = new QName("urn:fatca:fatcanotificationbase", "FATCANotificationCreateTs");
    private final static QName _CurrencyCd_QNAME = new QName("urn:fatca:fatcanotificationbase", "CurrencyCd");
    private final static QName _MoneyAmt_QNAME = new QName("urn:fatca:fatcanotificationbase", "MoneyAmt");
    private final static QName _CopiedToFATCAEntityId_QNAME = new QName("urn:fatca:fatcanotificationbase", "CopiedToFATCAEntityId");
    private final static QName _PaperRecordDocumentTypeCd_QNAME = new QName("urn:fatca:fatcanotificationbase", "PaperRecordDocumentTypeCd");
    private final static QName _RecordCnt_QNAME = new QName("urn:fatca:fatcanotificationbase", "RecordCnt");
    private final static QName _AddressFreeTxt_QNAME = new QName("urn:fatca:fatcanotificationbase", "AddressFreeTxt");
    private final static QName _HCTAContactNm_QNAME = new QName("urn:fatca:fatcanotificationbase", "HCTAContactNm");
    private final static QName _ReportingPeriodDt_QNAME = new QName("urn:fatca:fatcanotificationbase", "ReportingPeriodDt");
    private final static QName _OriginalPaperRecordMetadataGrp_QNAME = new QName("urn:fatca:fatcanotificationbase", "OriginalPaperRecordMetadataGrp");
    private final static QName _ActionRequestedDueDateTxt_QNAME = new QName("urn:fatca:fatcanotificationbase", "ActionRequestedDueDateTxt");
    private final static QName _TaxYear_QNAME = new QName("urn:fatca:fatcanotificationbase", "TaxYear");
    private final static QName _PooledReportRecordCnt_QNAME = new QName("urn:fatca:fatcanotificationbase", "PooledReportRecordCnt");
    private final static QName _PooledReportDetail_QNAME = new QName("urn:fatca:fatcanotificationbase", "PooledReportDetail");
    private final static QName _ReportingFIAddressGrp_QNAME = new QName("urn:fatca:fatcanotificationbase", "ReportingFIAddressGrp");
    private final static QName _FileCreateTs_QNAME = new QName("urn:fatca:fatcanotificationbase", "FileCreateTs");
    private final static QName _FATCAValidFileNotification_QNAME = new QName("urn:fatca:fatcainterimvalidfilenotification", "FATCAValidFileNotification");
    private final static QName _FATCAEntityReceiverId_QNAME = new QName("urn:fatca:fatcanotificationbase", "FATCAEntityReceiverId");
    private final static QName _FieldErrorGrp_QNAME = new QName("urn:fatca:fatcanotificationbase", "FieldErrorGrp");
    private final static QName _DocRefId_QNAME = new QName("urn:fatca:fatcanotificationbase", "DocRefId");
    private final static QName _OriginalFileMetadataGrp_QNAME = new QName("urn:fatca:fatcanotificationbase", "OriginalFileMetadataGrp");
    private final static QName _FieldLineNum_QNAME = new QName("urn:fatca:fatcanotificationbase", "FieldLineNum");
    private final static QName _PaperRecordRefId_QNAME = new QName("urn:fatca:fatcanotificationbase", "PaperRecordRefId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.twc.fatcaone.notification
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FATCAValidFileNotificationType }
     * 
     */
    public FATCAValidFileNotificationType createFATCAValidFileNotificationType() {
        return new FATCAValidFileNotificationType();
    }

    /**
     * Create an instance of {@link FATCANotificationHeaderGrpType }
     * 
     */
    public FATCANotificationHeaderGrpType createFATCANotificationHeaderGrpType() {
        return new FATCANotificationHeaderGrpType();
    }

    /**
     * Create an instance of {@link AddressGrpType }
     * 
     */
    public AddressGrpType createAddressGrpType() {
        return new AddressGrpType();
    }

    /**
     * Create an instance of {@link OriginalFileMetadataGrpType }
     * 
     */
    public OriginalFileMetadataGrpType createOriginalFileMetadataGrpType() {
        return new OriginalFileMetadataGrpType();
    }

    /**
     * Create an instance of {@link FieldErrorGrpType }
     * 
     */
    public FieldErrorGrpType createFieldErrorGrpType() {
        return new FieldErrorGrpType();
    }

    /**
     * Create an instance of {@link PooledReportDetailType }
     * 
     */
    public PooledReportDetailType createPooledReportDetailType() {
        return new PooledReportDetailType();
    }

    /**
     * Create an instance of {@link OriginalPaperRecordMetadataGrpType }
     * 
     */
    public OriginalPaperRecordMetadataGrpType createOriginalPaperRecordMetadataGrpType() {
        return new OriginalPaperRecordMetadataGrpType();
    }

    /**
     * Create an instance of {@link MonAmntType }
     * 
     */
    public MonAmntType createMonAmntType() {
        return new MonAmntType();
    }

    /**
     * Create an instance of {@link OriginalFileProcessingDataGrpType }
     * 
     */
    public OriginalFileProcessingDataGrpType createOriginalFileProcessingDataGrpType() {
        return new OriginalFileProcessingDataGrpType();
    }

    /**
     * Create an instance of {@link OriginalFileMessageSpecGrpType }
     * 
     */
    public OriginalFileMessageSpecGrpType createOriginalFileMessageSpecGrpType() {
        return new OriginalFileMessageSpecGrpType();
    }

    /**
     * Create an instance of {@link ActionRequestedGrpType }
     * 
     */
    public ActionRequestedGrpType createActionRequestedGrpType() {
        return new ActionRequestedGrpType();
    }

    /**
     * Create an instance of {@link RecordIdentifierType }
     * 
     */
    public RecordIdentifierType createRecordIdentifierType() {
        return new RecordIdentifierType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "FieldErrorCd")
    public JAXBElement<String> createFieldErrorCd(String value) {
        return new JAXBElement<String>(_FieldErrorCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "SenderFileId")
    public JAXBElement<String> createSenderFileId(String value) {
        return new JAXBElement<String>(_SenderFileId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OriginalFileMessageSpecGrpType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "OriginalFileMessageSpecGrp")
    public JAXBElement<OriginalFileMessageSpecGrpType> createOriginalFileMessageSpecGrp(OriginalFileMessageSpecGrpType value) {
        return new JAXBElement<OriginalFileMessageSpecGrpType>(_OriginalFileMessageSpecGrp_QNAME, OriginalFileMessageSpecGrpType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "AccountReportRecordCnt")
    public JAXBElement<BigInteger> createAccountReportRecordCnt(BigInteger value) {
        return new JAXBElement<BigInteger>(_AccountReportRecordCnt_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "CorrDocRefId")
    public JAXBElement<String> createCorrDocRefId(String value) {
        return new JAXBElement<String>(_CorrDocRefId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "AttachedPaperSubmissionFileNm")
    public JAXBElement<String> createAttachedPaperSubmissionFileNm(String value) {
        return new JAXBElement<String>(_AttachedPaperSubmissionFileNm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "DuplicateRecordInd")
    public JAXBElement<Boolean> createDuplicateRecordInd(Boolean value) {
        return new JAXBElement<Boolean>(_DuplicateRecordInd_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionRequestedGrpType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "ActionRequestedGrp")
    public JAXBElement<ActionRequestedGrpType> createActionRequestedGrp(ActionRequestedGrpType value) {
        return new JAXBElement<ActionRequestedGrpType>(_ActionRequestedGrp_QNAME, ActionRequestedGrpType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "ReportingFINm")
    public JAXBElement<String> createReportingFINm(String value) {
        return new JAXBElement<String>(_ReportingFINm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "AccountCnt")
    public JAXBElement<BigInteger> createAccountCnt(BigInteger value) {
        return new JAXBElement<BigInteger>(_AccountCnt_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "FinancialInstitutionCnt")
    public JAXBElement<BigInteger> createFinancialInstitutionCnt(BigInteger value) {
        return new JAXBElement<BigInteger>(_FinancialInstitutionCnt_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FATCANotificationCdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "FATCANotificationCd")
    public JAXBElement<FATCANotificationCdType> createFATCANotificationCd(FATCANotificationCdType value) {
        return new JAXBElement<FATCANotificationCdType>(_FATCANotificationCd_QNAME, FATCANotificationCdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "FATCANotificationRefId")
    public JAXBElement<String> createFATCANotificationRefId(String value) {
        return new JAXBElement<String>(_FATCANotificationRefId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FatcaAcctPoolReportTypeCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "AccountPoolReportTypeCd")
    public JAXBElement<FatcaAcctPoolReportTypeCodeType> createAccountPoolReportTypeCd(FatcaAcctPoolReportTypeCodeType value) {
        return new JAXBElement<FatcaAcctPoolReportTypeCodeType>(_AccountPoolReportTypeCd_QNAME, FatcaAcctPoolReportTypeCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "MessageRefId")
    public JAXBElement<String> createMessageRefId(String value) {
        return new JAXBElement<String>(_MessageRefId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "IDESTransmissionId")
    public JAXBElement<String> createIDESTransmissionId(String value) {
        return new JAXBElement<String>(_IDESTransmissionId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OriginalFileProcessingDataGrpType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "OriginalFileProcessingDataGrp")
    public JAXBElement<OriginalFileProcessingDataGrpType> createOriginalFileProcessingDataGrp(OriginalFileProcessingDataGrpType value) {
        return new JAXBElement<OriginalFileProcessingDataGrpType>(_OriginalFileProcessingDataGrp_QNAME, OriginalFileProcessingDataGrpType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonAmntType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "AccountBalanceAmount")
    public JAXBElement<MonAmntType> createAccountBalanceAmount(MonAmntType value) {
        return new JAXBElement<MonAmntType>(_AccountBalanceAmount_QNAME, MonAmntType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileTypeCdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "FileTypeCd")
    public JAXBElement<FileTypeCdType> createFileTypeCd(FileTypeCdType value) {
        return new JAXBElement<FileTypeCdType>(_FileTypeCd_QNAME, FileTypeCdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "FieldNm")
    public JAXBElement<String> createFieldNm(String value) {
        return new JAXBElement<String>(_FieldNm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "SendingCompanyGIIN")
    public JAXBElement<String> createSendingCompanyGIIN(String value) {
        return new JAXBElement<String>(_SendingCompanyGIIN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "PooledReportInd")
    public JAXBElement<Boolean> createPooledReportInd(Boolean value) {
        return new JAXBElement<Boolean>(_PooledReportInd_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "OriginalIDESTransmissionId")
    public JAXBElement<String> createOriginalIDESTransmissionId(String value) {
        return new JAXBElement<String>(_OriginalIDESTransmissionId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "CorrMessageRefId")
    public JAXBElement<String> createCorrMessageRefId(String value) {
        return new JAXBElement<String>(_CorrMessageRefId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ISO3166Alpha2CountryCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "TransmittingCountryCd")
    public JAXBElement<ISO3166Alpha2CountryCodeType> createTransmittingCountryCd(ISO3166Alpha2CountryCodeType value) {
        return new JAXBElement<ISO3166Alpha2CountryCodeType>(_TransmittingCountryCd_QNAME, ISO3166Alpha2CountryCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "FATCAEntitySenderId")
    public JAXBElement<String> createFATCAEntitySenderId(String value) {
        return new JAXBElement<String>(_FATCAEntitySenderId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecordIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "RecordIdentifier")
    public JAXBElement<RecordIdentifierType> createRecordIdentifier(RecordIdentifierType value) {
        return new JAXBElement<RecordIdentifierType>(_RecordIdentifier_QNAME, RecordIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "RequestSubmissionDt")
    public JAXBElement<XMLGregorianCalendar> createRequestSubmissionDt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RequestSubmissionDt_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "ActionRequestedTxt")
    public JAXBElement<String> createActionRequestedTxt(String value) {
        return new JAXBElement<String>(_ActionRequestedTxt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "ReportingFIGIIN")
    public JAXBElement<String> createReportingFIGIIN(String value) {
        return new JAXBElement<String>(_ReportingFIGIIN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ISO3166Alpha2CountryCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "CountryCd")
    public JAXBElement<ISO3166Alpha2CountryCodeType> createCountryCd(ISO3166Alpha2CountryCodeType value) {
        return new JAXBElement<ISO3166Alpha2CountryCodeType>(_CountryCd_QNAME, ISO3166Alpha2CountryCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "PotentialEffectTxt")
    public JAXBElement<String> createPotentialEffectTxt(String value) {
        return new JAXBElement<String>(_PotentialEffectTxt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "PaperRecordInd")
    public JAXBElement<Boolean> createPaperRecordInd(Boolean value) {
        return new JAXBElement<Boolean>(_PaperRecordInd_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "MessageTypeCd")
    public JAXBElement<MessageTypeType> createMessageTypeCd(MessageTypeType value) {
        return new JAXBElement<MessageTypeType>(_MessageTypeCd_QNAME, MessageTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "ContactInformationTxt")
    public JAXBElement<String> createContactInformationTxt(String value) {
        return new JAXBElement<String>(_ContactInformationTxt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "NotificationContentTxt")
    public JAXBElement<String> createNotificationContentTxt(String value) {
        return new JAXBElement<String>(_NotificationContentTxt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "HCTATreatyStampTxt")
    public JAXBElement<String> createHCTATreatyStampTxt(String value) {
        return new JAXBElement<String>(_HCTATreatyStampTxt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "IDESSendingTs")
    public JAXBElement<String> createIDESSendingTs(String value) {
        return new JAXBElement<String>(_IDESSendingTs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "FieldErrorTxt")
    public JAXBElement<String> createFieldErrorTxt(String value) {
        return new JAXBElement<String>(_FieldErrorTxt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ISO3166Alpha2CountryCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "ReceivingCountryCd")
    public JAXBElement<ISO3166Alpha2CountryCodeType> createReceivingCountryCd(ISO3166Alpha2CountryCodeType value) {
        return new JAXBElement<ISO3166Alpha2CountryCodeType>(_ReceivingCountryCd_QNAME, ISO3166Alpha2CountryCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressGrpType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "HCTAAddressGrp")
    public JAXBElement<AddressGrpType> createHCTAAddressGrp(AddressGrpType value) {
        return new JAXBElement<AddressGrpType>(_HCTAAddressGrp_QNAME, AddressGrpType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "UncompressedFileSizeKBQty")
    public JAXBElement<BigInteger> createUncompressedFileSizeKBQty(BigInteger value) {
        return new JAXBElement<BigInteger>(_UncompressedFileSizeKBQty_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "AttachedCARFileNm")
    public JAXBElement<String> createAttachedCARFileNm(String value) {
        return new JAXBElement<String>(_AttachedCARFileNm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FatcaDocTypeIndicType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "DocTypeIndicCd")
    public JAXBElement<FatcaDocTypeIndicType> createDocTypeIndicCd(FatcaDocTypeIndicType value) {
        return new JAXBElement<FatcaDocTypeIndicType>(_DocTypeIndicCd_QNAME, FatcaDocTypeIndicType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "FieldPartNum")
    public JAXBElement<BigInteger> createFieldPartNum(BigInteger value) {
        return new JAXBElement<BigInteger>(_FieldPartNum_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "RecordErrorTypeCd")
    public JAXBElement<String> createRecordErrorTypeCd(String value) {
        return new JAXBElement<String>(_RecordErrorTypeCd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "RequestAuthorizerNm")
    public JAXBElement<String> createRequestAuthorizerNm(String value) {
        return new JAXBElement<String>(_RequestAuthorizerNm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FATCANotificationHeaderGrpType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "FATCANotificationHeaderGrp")
    public JAXBElement<FATCANotificationHeaderGrpType> createFATCANotificationHeaderGrp(FATCANotificationHeaderGrpType value) {
        return new JAXBElement<FATCANotificationHeaderGrpType>(_FATCANotificationHeaderGrp_QNAME, FATCANotificationHeaderGrpType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "FATCANotificationCreateTs")
    public JAXBElement<String> createFATCANotificationCreateTs(String value) {
        return new JAXBElement<String>(_FATCANotificationCreateTs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ISO4217Alpha3CurrCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "CurrencyCd")
    public JAXBElement<ISO4217Alpha3CurrCodeType> createCurrencyCd(ISO4217Alpha3CurrCodeType value) {
        return new JAXBElement<ISO4217Alpha3CurrCodeType>(_CurrencyCd_QNAME, ISO4217Alpha3CurrCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "MoneyAmt")
    public JAXBElement<BigDecimal> createMoneyAmt(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_MoneyAmt_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "CopiedToFATCAEntityId")
    public JAXBElement<String> createCopiedToFATCAEntityId(String value) {
        return new JAXBElement<String>(_CopiedToFATCAEntityId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PaperRecordDocumentTypeCdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "PaperRecordDocumentTypeCd")
    public JAXBElement<PaperRecordDocumentTypeCdType> createPaperRecordDocumentTypeCd(PaperRecordDocumentTypeCdType value) {
        return new JAXBElement<PaperRecordDocumentTypeCdType>(_PaperRecordDocumentTypeCd_QNAME, PaperRecordDocumentTypeCdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "RecordCnt")
    public JAXBElement<BigInteger> createRecordCnt(BigInteger value) {
        return new JAXBElement<BigInteger>(_RecordCnt_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "AddressFreeTxt")
    public JAXBElement<String> createAddressFreeTxt(String value) {
        return new JAXBElement<String>(_AddressFreeTxt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "HCTAContactNm")
    public JAXBElement<String> createHCTAContactNm(String value) {
        return new JAXBElement<String>(_HCTAContactNm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "ReportingPeriodDt")
    public JAXBElement<XMLGregorianCalendar> createReportingPeriodDt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ReportingPeriodDt_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OriginalPaperRecordMetadataGrpType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "OriginalPaperRecordMetadataGrp")
    public JAXBElement<OriginalPaperRecordMetadataGrpType> createOriginalPaperRecordMetadataGrp(OriginalPaperRecordMetadataGrpType value) {
        return new JAXBElement<OriginalPaperRecordMetadataGrpType>(_OriginalPaperRecordMetadataGrp_QNAME, OriginalPaperRecordMetadataGrpType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "ActionRequestedDueDateTxt")
    public JAXBElement<String> createActionRequestedDueDateTxt(String value) {
        return new JAXBElement<String>(_ActionRequestedDueDateTxt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "TaxYear")
    public JAXBElement<XMLGregorianCalendar> createTaxYear(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TaxYear_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "PooledReportRecordCnt")
    public JAXBElement<BigInteger> createPooledReportRecordCnt(BigInteger value) {
        return new JAXBElement<BigInteger>(_PooledReportRecordCnt_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PooledReportDetailType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "PooledReportDetail")
    public JAXBElement<PooledReportDetailType> createPooledReportDetail(PooledReportDetailType value) {
        return new JAXBElement<PooledReportDetailType>(_PooledReportDetail_QNAME, PooledReportDetailType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressGrpType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "ReportingFIAddressGrp")
    public JAXBElement<AddressGrpType> createReportingFIAddressGrp(AddressGrpType value) {
        return new JAXBElement<AddressGrpType>(_ReportingFIAddressGrp_QNAME, AddressGrpType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "FileCreateTs")
    public JAXBElement<String> createFileCreateTs(String value) {
        return new JAXBElement<String>(_FileCreateTs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FATCAValidFileNotificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcainterimvalidfilenotification", name = "FATCAValidFileNotification")
    public JAXBElement<FATCAValidFileNotificationType> createFATCAValidFileNotification(FATCAValidFileNotificationType value) {
        return new JAXBElement<FATCAValidFileNotificationType>(_FATCAValidFileNotification_QNAME, FATCAValidFileNotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "FATCAEntityReceiverId")
    public JAXBElement<String> createFATCAEntityReceiverId(String value) {
        return new JAXBElement<String>(_FATCAEntityReceiverId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldErrorGrpType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "FieldErrorGrp")
    public JAXBElement<FieldErrorGrpType> createFieldErrorGrp(FieldErrorGrpType value) {
        return new JAXBElement<FieldErrorGrpType>(_FieldErrorGrp_QNAME, FieldErrorGrpType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "DocRefId")
    public JAXBElement<String> createDocRefId(String value) {
        return new JAXBElement<String>(_DocRefId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OriginalFileMetadataGrpType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "OriginalFileMetadataGrp")
    public JAXBElement<OriginalFileMetadataGrpType> createOriginalFileMetadataGrp(OriginalFileMetadataGrpType value) {
        return new JAXBElement<OriginalFileMetadataGrpType>(_OriginalFileMetadataGrp_QNAME, OriginalFileMetadataGrpType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "FieldLineNum")
    public JAXBElement<BigInteger> createFieldLineNum(BigInteger value) {
        return new JAXBElement<BigInteger>(_FieldLineNum_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fatca:fatcanotificationbase", name = "PaperRecordRefId")
    public JAXBElement<String> createPaperRecordRefId(String value) {
        return new JAXBElement<String>(_PaperRecordRefId_QNAME, String.class, null, value);
    }

}
