//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.01 at 03:58:04 PM IST 
//


package com.twc.fatcaone.notification;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;Component xmlns="urn:fatca:fatcanotificationbase" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;DictionaryEntryNm&gt;Original File Processing Data Group Type&lt;/DictionaryEntryNm&gt;&lt;MajorVersionNum&gt;1&lt;/MajorVersionNum&gt;&lt;MinorVersionNum&gt;0&lt;/MinorVersionNum&gt;&lt;VersionEffectiveBeginDt&gt;2014-08-12&lt;/VersionEffectiveBeginDt&gt;&lt;VersionDescriptionTxt&gt;Initial Version&lt;/VersionDescriptionTxt&gt;&lt;DescriptionTxt&gt;Type for details about FATCA report processing data&lt;/DescriptionTxt&gt;
 * 				&lt;/Component&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for OriginalFileProcessingDataGrpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OriginalFileProcessingDataGrpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FileTypeCd"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FinancialInstitutionCnt" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}RecordCnt" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}AccountReportRecordCnt" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}PooledReportRecordCnt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OriginalFileProcessingDataGrpType", propOrder = {
    "fileTypeCd",
    "financialInstitutionCnt",
    "recordCnt",
    "accountReportRecordCnt",
    "pooledReportRecordCnt"
})
public class OriginalFileProcessingDataGrpType {

    @XmlElement(name = "FileTypeCd", required = true)
    protected FileTypeCdType fileTypeCd;
    @XmlElement(name = "FinancialInstitutionCnt")
    protected BigInteger financialInstitutionCnt;
    @XmlElement(name = "RecordCnt")
    protected BigInteger recordCnt;
    @XmlElement(name = "AccountReportRecordCnt")
    protected BigInteger accountReportRecordCnt;
    @XmlElement(name = "PooledReportRecordCnt")
    protected BigInteger pooledReportRecordCnt;

    /**
     * Gets the value of the fileTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link FileTypeCdType }
     *     
     */
    public FileTypeCdType getFileTypeCd() {
        return fileTypeCd;
    }

    /**
     * Sets the value of the fileTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileTypeCdType }
     *     
     */
    public void setFileTypeCd(FileTypeCdType value) {
        this.fileTypeCd = value;
    }

    /**
     * Gets the value of the financialInstitutionCnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFinancialInstitutionCnt() {
        return financialInstitutionCnt;
    }

    /**
     * Sets the value of the financialInstitutionCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFinancialInstitutionCnt(BigInteger value) {
        this.financialInstitutionCnt = value;
    }

    /**
     * Gets the value of the recordCnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecordCnt() {
        return recordCnt;
    }

    /**
     * Sets the value of the recordCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecordCnt(BigInteger value) {
        this.recordCnt = value;
    }

    /**
     * Gets the value of the accountReportRecordCnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccountReportRecordCnt() {
        return accountReportRecordCnt;
    }

    /**
     * Sets the value of the accountReportRecordCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccountReportRecordCnt(BigInteger value) {
        this.accountReportRecordCnt = value;
    }

    /**
     * Gets the value of the pooledReportRecordCnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPooledReportRecordCnt() {
        return pooledReportRecordCnt;
    }

    /**
     * Sets the value of the pooledReportRecordCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPooledReportRecordCnt(BigInteger value) {
        this.pooledReportRecordCnt = value;
    }

}
