//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.01 at 03:58:04 PM IST 
//


package com.twc.fatcaone.notification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;Component xmlns="urn:fatca:fatcanotificationbase" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;DictionaryEntryNm&gt;Original Paper Record Metadata Group Type&lt;/DictionaryEntryNm&gt;&lt;MajorVersionNum&gt;1&lt;/MajorVersionNum&gt;&lt;MinorVersionNum&gt;0&lt;/MinorVersionNum&gt;&lt;VersionEffectiveBeginDt&gt;2014-08-24&lt;/VersionEffectiveBeginDt&gt;&lt;VersionDescriptionTxt&gt;Initial Version&lt;/VersionDescriptionTxt&gt;&lt;DescriptionTxt&gt;Type for a group that defines the information contained in the IDES Metadata&lt;/DescriptionTxt&gt;
 * 				&lt;/Component&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for OriginalPaperRecordMetadataGrpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OriginalPaperRecordMetadataGrpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}PaperRecordRefId"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}AttachedPaperSubmissionFileNm" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}PaperRecordDocumentTypeCd"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}PooledReportInd"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OriginalPaperRecordMetadataGrpType", propOrder = {
    "paperRecordRefId",
    "attachedPaperSubmissionFileNm",
    "paperRecordDocumentTypeCd",
    "pooledReportInd"
})
public class OriginalPaperRecordMetadataGrpType {

    @XmlElement(name = "PaperRecordRefId", required = true)
    protected String paperRecordRefId;
    @XmlElement(name = "AttachedPaperSubmissionFileNm")
    protected String attachedPaperSubmissionFileNm;
    @XmlElement(name = "PaperRecordDocumentTypeCd", required = true)
    protected PaperRecordDocumentTypeCdType paperRecordDocumentTypeCd;
    @XmlElement(name = "PooledReportInd")
    protected boolean pooledReportInd;

    /**
     * Gets the value of the paperRecordRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaperRecordRefId() {
        return paperRecordRefId;
    }

    /**
     * Sets the value of the paperRecordRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaperRecordRefId(String value) {
        this.paperRecordRefId = value;
    }

    /**
     * Gets the value of the attachedPaperSubmissionFileNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachedPaperSubmissionFileNm() {
        return attachedPaperSubmissionFileNm;
    }

    /**
     * Sets the value of the attachedPaperSubmissionFileNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachedPaperSubmissionFileNm(String value) {
        this.attachedPaperSubmissionFileNm = value;
    }

    /**
     * Gets the value of the paperRecordDocumentTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link PaperRecordDocumentTypeCdType }
     *     
     */
    public PaperRecordDocumentTypeCdType getPaperRecordDocumentTypeCd() {
        return paperRecordDocumentTypeCd;
    }

    /**
     * Sets the value of the paperRecordDocumentTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaperRecordDocumentTypeCdType }
     *     
     */
    public void setPaperRecordDocumentTypeCd(PaperRecordDocumentTypeCdType value) {
        this.paperRecordDocumentTypeCd = value;
    }

    /**
     * Gets the value of the pooledReportInd property.
     * 
     */
    public boolean isPooledReportInd() {
        return pooledReportInd;
    }

    /**
     * Sets the value of the pooledReportInd property.
     * 
     */
    public void setPooledReportInd(boolean value) {
        this.pooledReportInd = value;
    }

}
