//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.01 at 03:58:04 PM IST 
//


package com.twc.fatcaone.notification;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;Component xmlns="urn:fatca:fatcanotificationbase" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;DictionaryEntryNm&gt;Original File Metadata Group Type&lt;/DictionaryEntryNm&gt;&lt;MajorVersionNum&gt;1&lt;/MajorVersionNum&gt;&lt;MinorVersionNum&gt;0&lt;/MinorVersionNum&gt;&lt;VersionEffectiveBeginDt&gt;2014-08-24&lt;/VersionEffectiveBeginDt&gt;&lt;VersionDescriptionTxt&gt;Initial Version&lt;/VersionDescriptionTxt&gt;&lt;DescriptionTxt&gt;Type for a group that defines the information contained in the original file metadata&lt;/DescriptionTxt&gt;
 * 				&lt;/Component&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for OriginalFileMetadataGrpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OriginalFileMetadataGrpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}IDESTransmissionId"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}IDESSendingTs"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}OriginalIDESTransmissionId" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}SenderFileId"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}UncompressedFileSizeKBQty" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OriginalFileMetadataGrpType", propOrder = {
    "idesTransmissionId",
    "idesSendingTs",
    "originalIDESTransmissionId",
    "senderFileId",
    "uncompressedFileSizeKBQty"
})
public class OriginalFileMetadataGrpType {

    @XmlElement(name = "IDESTransmissionId", required = true)
    protected String idesTransmissionId;
    @XmlElement(name = "IDESSendingTs", required = true)
    protected String idesSendingTs;
    @XmlElement(name = "OriginalIDESTransmissionId")
    protected String originalIDESTransmissionId;
    @XmlElement(name = "SenderFileId", required = true)
    protected String senderFileId;
    @XmlElement(name = "UncompressedFileSizeKBQty")
    protected BigInteger uncompressedFileSizeKBQty;

    /**
     * Gets the value of the idesTransmissionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDESTransmissionId() {
        return idesTransmissionId;
    }

    /**
     * Sets the value of the idesTransmissionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDESTransmissionId(String value) {
        this.idesTransmissionId = value;
    }

    /**
     * Gets the value of the idesSendingTs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDESSendingTs() {
        return idesSendingTs;
    }

    /**
     * Sets the value of the idesSendingTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDESSendingTs(String value) {
        this.idesSendingTs = value;
    }

    /**
     * Gets the value of the originalIDESTransmissionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalIDESTransmissionId() {
        return originalIDESTransmissionId;
    }

    /**
     * Sets the value of the originalIDESTransmissionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalIDESTransmissionId(String value) {
        this.originalIDESTransmissionId = value;
    }

    /**
     * Gets the value of the senderFileId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderFileId() {
        return senderFileId;
    }

    /**
     * Sets the value of the senderFileId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderFileId(String value) {
        this.senderFileId = value;
    }

    /**
     * Gets the value of the uncompressedFileSizeKBQty property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUncompressedFileSizeKBQty() {
        return uncompressedFileSizeKBQty;
    }

    /**
     * Sets the value of the uncompressedFileSizeKBQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUncompressedFileSizeKBQty(BigInteger value) {
        this.uncompressedFileSizeKBQty = value;
    }

}
