//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.01 at 03:58:04 PM IST 
//


package com.twc.fatcaone.notification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;Component xmlns="urn:fatca:fatcanotificationbase" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;DictionaryEntryNm&gt;Original File Message Spec Group Type&lt;/DictionaryEntryNm&gt;&lt;MajorVersionNum&gt;1&lt;/MajorVersionNum&gt;&lt;MinorVersionNum&gt;0&lt;/MinorVersionNum&gt;&lt;VersionEffectiveBeginDt&gt;2014-08-24&lt;/VersionEffectiveBeginDt&gt;&lt;VersionDescriptionTxt&gt;Initial Version&lt;/VersionDescriptionTxt&gt;&lt;DescriptionTxt&gt;Type for a group that defines the information contained in the original file MessageSpec&lt;/DescriptionTxt&gt;
 * 				&lt;/Component&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for OriginalFileMessageSpecGrpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OriginalFileMessageSpecGrpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}MessageRefId"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}CorrMessageRefId" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}SendingCompanyGIIN" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}TransmittingCountryCd"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}ReceivingCountryCd"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}MessageTypeCd"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}ReportingPeriodDt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OriginalFileMessageSpecGrpType", propOrder = {
    "messageRefId",
    "corrMessageRefId",
    "sendingCompanyGIIN",
    "transmittingCountryCd",
    "receivingCountryCd",
    "messageTypeCd",
    "reportingPeriodDt"
})
public class OriginalFileMessageSpecGrpType {

    @XmlElement(name = "MessageRefId", required = true)
    protected String messageRefId;
    @XmlElement(name = "CorrMessageRefId")
    protected String corrMessageRefId;
    @XmlElement(name = "SendingCompanyGIIN")
    protected String sendingCompanyGIIN;
    @XmlElement(name = "TransmittingCountryCd", required = true)
    protected ISO3166Alpha2CountryCodeType transmittingCountryCd;
    @XmlElement(name = "ReceivingCountryCd", required = true)
    protected ISO3166Alpha2CountryCodeType receivingCountryCd;
    @XmlElement(name = "MessageTypeCd", required = true)
    protected MessageTypeType messageTypeCd;
    @XmlElement(name = "ReportingPeriodDt", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar reportingPeriodDt;

    /**
     * Gets the value of the messageRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageRefId() {
        return messageRefId;
    }

    /**
     * Sets the value of the messageRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageRefId(String value) {
        this.messageRefId = value;
    }

    /**
     * Gets the value of the corrMessageRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrMessageRefId() {
        return corrMessageRefId;
    }

    /**
     * Sets the value of the corrMessageRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrMessageRefId(String value) {
        this.corrMessageRefId = value;
    }

    /**
     * Gets the value of the sendingCompanyGIIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendingCompanyGIIN() {
        return sendingCompanyGIIN;
    }

    /**
     * Sets the value of the sendingCompanyGIIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendingCompanyGIIN(String value) {
        this.sendingCompanyGIIN = value;
    }

    /**
     * Gets the value of the transmittingCountryCd property.
     * 
     * @return
     *     possible object is
     *     {@link ISO3166Alpha2CountryCodeType }
     *     
     */
    public ISO3166Alpha2CountryCodeType getTransmittingCountryCd() {
        return transmittingCountryCd;
    }

    /**
     * Sets the value of the transmittingCountryCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISO3166Alpha2CountryCodeType }
     *     
     */
    public void setTransmittingCountryCd(ISO3166Alpha2CountryCodeType value) {
        this.transmittingCountryCd = value;
    }

    /**
     * Gets the value of the receivingCountryCd property.
     * 
     * @return
     *     possible object is
     *     {@link ISO3166Alpha2CountryCodeType }
     *     
     */
    public ISO3166Alpha2CountryCodeType getReceivingCountryCd() {
        return receivingCountryCd;
    }

    /**
     * Sets the value of the receivingCountryCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISO3166Alpha2CountryCodeType }
     *     
     */
    public void setReceivingCountryCd(ISO3166Alpha2CountryCodeType value) {
        this.receivingCountryCd = value;
    }

    /**
     * Gets the value of the messageTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link MessageTypeType }
     *     
     */
    public MessageTypeType getMessageTypeCd() {
        return messageTypeCd;
    }

    /**
     * Sets the value of the messageTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageTypeType }
     *     
     */
    public void setMessageTypeCd(MessageTypeType value) {
        this.messageTypeCd = value;
    }

    /**
     * Gets the value of the reportingPeriodDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportingPeriodDt() {
        return reportingPeriodDt;
    }

    /**
     * Sets the value of the reportingPeriodDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportingPeriodDt(XMLGregorianCalendar value) {
        this.reportingPeriodDt = value;
    }

}
