//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.01 at 03:58:04 PM IST 
//


package com.twc.fatcaone.notification;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaperRecordDocumentTypeCdType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PaperRecordDocumentTypeCdType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NEW"/>
 *     &lt;enumeration value="AMENDED"/>
 *     &lt;enumeration value="CORRECTED"/>
 *     &lt;enumeration value="VOID"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PaperRecordDocumentTypeCdType")
@XmlEnum
public enum PaperRecordDocumentTypeCdType {


    /**
     * New Record
     * 
     */
    NEW,

    /**
     * Amended Record
     * 
     */
    AMENDED,

    /**
     * Corrected Record
     * 
     */
    CORRECTED,

    /**
     * Void Record
     * 
     */
    VOID;

    public String value() {
        return name();
    }

    public static PaperRecordDocumentTypeCdType fromValue(String v) {
        return valueOf(v);
    }

}
