//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.01 at 03:58:04 PM IST 
//


package com.twc.fatcaone.notification;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;Component xmlns="urn:fatca:fatcanotificationbase" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;DictionaryEntryNm&gt;Pooled Report Detail Type&lt;/DictionaryEntryNm&gt;&lt;MajorVersionNum&gt;1&lt;/MajorVersionNum&gt;&lt;MinorVersionNum&gt;0&lt;/MinorVersionNum&gt;&lt;VersionEffectiveBeginDt&gt;2014-08-12&lt;/VersionEffectiveBeginDt&gt;&lt;VersionDescriptionTxt&gt;Initial Version&lt;/VersionDescriptionTxt&gt;&lt;DescriptionTxt&gt;FATCA Pooled Report Detail Type&lt;/DescriptionTxt&gt;
 * 				&lt;/Component&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for PooledReportDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PooledReportDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}RecordIdentifier"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}AccountCnt"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}AccountBalanceAmount"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}AccountPoolReportTypeCd"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PooledReportDetailType", propOrder = {
    "recordIdentifier",
    "accountCnt",
    "accountBalanceAmount",
    "accountPoolReportTypeCd"
})
public class PooledReportDetailType {

    @XmlElement(name = "RecordIdentifier", required = true)
    protected RecordIdentifierType recordIdentifier;
    @XmlElement(name = "AccountCnt", required = true)
    protected BigInteger accountCnt;
    @XmlElement(name = "AccountBalanceAmount", required = true)
    protected MonAmntType accountBalanceAmount;
    @XmlElement(name = "AccountPoolReportTypeCd", required = true)
    protected FatcaAcctPoolReportTypeCodeType accountPoolReportTypeCd;

    /**
     * Gets the value of the recordIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link RecordIdentifierType }
     *     
     */
    public RecordIdentifierType getRecordIdentifier() {
        return recordIdentifier;
    }

    /**
     * Sets the value of the recordIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordIdentifierType }
     *     
     */
    public void setRecordIdentifier(RecordIdentifierType value) {
        this.recordIdentifier = value;
    }

    /**
     * Gets the value of the accountCnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccountCnt() {
        return accountCnt;
    }

    /**
     * Sets the value of the accountCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccountCnt(BigInteger value) {
        this.accountCnt = value;
    }

    /**
     * Gets the value of the accountBalanceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonAmntType }
     *     
     */
    public MonAmntType getAccountBalanceAmount() {
        return accountBalanceAmount;
    }

    /**
     * Sets the value of the accountBalanceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonAmntType }
     *     
     */
    public void setAccountBalanceAmount(MonAmntType value) {
        this.accountBalanceAmount = value;
    }

    /**
     * Gets the value of the accountPoolReportTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link FatcaAcctPoolReportTypeCodeType }
     *     
     */
    public FatcaAcctPoolReportTypeCodeType getAccountPoolReportTypeCd() {
        return accountPoolReportTypeCd;
    }

    /**
     * Sets the value of the accountPoolReportTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link FatcaAcctPoolReportTypeCodeType }
     *     
     */
    public void setAccountPoolReportTypeCd(FatcaAcctPoolReportTypeCodeType value) {
        this.accountPoolReportTypeCd = value;
    }

}
